package com.macrocom.model;
// Generated Sep 16, 2021 9:45:39 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private int id;
	private String name;
	private Set employees = new HashSet(0);

	public Department() {
	}

	public Department(int id) {
		this.id = id;
	}

	public Department(int id, String name, Set employees) {
		this.id = id;
		this.name = name;
		this.employees = employees;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set employees) {
		this.employees = employees;
	}

}
